tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
cask "osxfuse"
brew "coreutils"
brew "curl"
brew "diceware"
brew "fish"
brew "git"
brew "highlight"
brew "lazygit"
brew "mas"
brew "micro"
brew "pipenv"
brew "pwgen"
brew "python"
brew "sshfs"
brew "stow"
brew "yarn"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
cask "adoptopenjdk11"
cask "aerial"
cask "alfred"
cask "appcleaner"
cask "docker"
cask "font-jetbrains-mono"
cask "google-chrome"
cask "intellij-idea"
cask "iterm2"
cask "league-of-legends"
cask "pock"
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlstephen"
cask "sequel-pro"
cask "spotify"
cask "steam"
cask "sublime-text"
cask "telegram"
cask "whatsapp"
mas "1Blocker", id: 1107421413
mas "1Password 7", id: 1333542190
mas "Clear", id: 504544917
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
